
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
      extra_hosts:
        - "host.docker.internal:192.168.0.144"
    image: openhands-jesse:latest
    container_name: openhands-app-${DATE:-}
    environment:
      #- SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:open_hands_cuda_runtime}
      #- SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.openhands.dev/openhands/runtime:0.60-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of ~/.openhands for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
      - DEBUG=true
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:192.168.0.144"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
                #device_ids: ['0']
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true
